INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est la',NULL,NULL)
,('ut labore et do',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmo',NULL,NULL)
,('aute irure dolor in reprehen',NULL,NULL)
,('exercitation ullamco l',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ',NULL,NULL)
,('minim ',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ',NULL,NULL)
,('borum.Lorem ipsum dolor sit amet, consec',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',NULL,NULL)
,('deseru',NULL,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in',NULL,NULL)
,('sint occaecat cupidatat non ',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in vo',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat n',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut lab',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisci',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Ex',NULL,NULL)
,('adipis',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui o',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fug',NULL,NULL)
,('et dolo',NULL,NULL)
,('magna aliqua. Ut enim ad minim ',NULL,NULL)
,('magna',NULL,NULL)
,('Duis aute irure dolor in repreh',NULL,NULL)
,('i',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ma',NULL,NULL)
,('quis ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non proident, sunt in cul',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui o',NULL,NULL)
,('in reprehenderit in voluptate velit',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, q',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut ',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qu',NULL,NULL)
,('dolor in reprehenderit in volupt',NULL,NULL)
,('anim id est la',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qu',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore e',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('enim ad minim veniam, quis nostrud exercitatio',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no',NULL,NULL)
,('lab',NULL,NULL)
,('culpa qui of',NULL,NULL)
,('m.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ei',NULL,NULL)
,('irure dolor in reprehenderit in voluptat',NULL,NULL)
,('in culpa qui officia deserunt mollit anim id',NULL,NULL)
,('deserunt mol',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectet',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in',NULL,NULL)
,('id es',NULL,NULL)
,('labore et dolore ',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',NULL,NULL)
,('consectetur adipis',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo con',NULL,NULL)
,('non p',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute i',NULL,NULL)
,('orum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut la',NULL,NULL)
,('deserunt mollit anim id est lab',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ipsum dolor',NULL,NULL)
,('id est laborum.Lorem ipsum dolor',NULL,NULL)
,('magna aliqua. Ut enim ad minim venia',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in v',NULL,NULL)
,('sunt in culpa',NULL,NULL)
,('aute irure dolor in ',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nis',NULL,NULL)
,('Excepteur sint ',NULL,NULL)
,('esse c',NULL,NULL)
,('Excepteur sint ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('officia deserunt mollit anim id est labor',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu',NULL,NULL)
,('non proident, sunt in',NULL,NULL)
,('laborum.Lorem ipsum',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('Duis aute irure dolor in reprehender',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo conse',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consec',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupida',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore magna aliqua. Ut enim ad minim veniam,',NULL,NULL)
,('non proident, sunt in culpa qu',NULL,NULL)
,('commodo consequat. Duis aut',NULL,NULL)
,('veniam, quis nostrud exercitati',NULL,NULL)
,('cillum ',NULL,NULL)
,('conseq',NULL,NULL)
,('Ut enim ad minim veniam, qui',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in ',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolor',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('pariatur. Excepteur sint occaecat cupidatat non proident, su',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,NULL)
,('nostrud exerci',NULL,NULL)
,('dolore eu fugiat nu',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui ',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod t',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consect',NULL,NULL)
,('amet, consectetur adipisci',NULL,NULL)
,('deserunt mollit anim id est ',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute ',NULL,NULL)
,('non proident, sunt in cu',NULL,NULL)
,('culpa qui officia deserunt mollit an',NULL,NULL)
,('el',NULL,NULL)
,('do eiusmod tempor incididunt ut labore et dolore ma',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore ',NULL,NULL)
,('laborum.Lorem ip',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, se',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proid',NULL,NULL)
,('dolor sit ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. E',NULL,NULL)
,('ex ea',NULL,NULL)
,('et dolore magna aliqua. Ut enim a',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo ',NULL,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun',NULL,NULL)
,('adipiscing elit, sed d',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupida',NULL,NULL)
,('ullamco laboris nisi ut aliq',NULL,NULL)
,('minim ve',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Ut',NULL,NULL)
,('anim id est laboru',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad min',NULL,NULL)
,('u',NULL,NULL)
,('Ut enim ad mini',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qui',NULL,NULL)
,('laboris nisi ut aliquip e',NULL,NULL)
,('Excepteur sint occaecat cu',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupta',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('irure dolor in repreh',NULL,NULL)
,('laboris n',NULL,NULL)
,('aliqua. Ut enim ad mini',NULL,NULL)
,('non proident, sunt in culpa qui off',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt moll',NULL,NULL)
,('incididunt ut labo',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud ',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia d',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea com',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore eu fugiat nulla pariatur. Excepteur sint occaec',NULL,NULL)
,('id est la',NULL,NULL)
,('minim veniam,',NULL,NULL)
,('in',NULL,NULL)
,('ut aliquip ex ea commo',NULL,NULL)
,('orum',NULL,NULL)
,('borum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmo',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore magna aliq',NULL,NULL)
,('ut labore et dolore magna aliqu',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('tempor incididunt ut labore et dolore magna aliqua. Ut eni',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et ',NULL,NULL)
,('ullamco laboris nisi ut',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla paria',NULL,NULL)
,('magna aliqua. Ut enim ',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pari',NULL,NULL)
,('elit, sed',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat n',NULL,NULL)
,('sit amet, consectetur adip',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in voluptate velit esse cillum dolore eu fugiat nulla par',NULL,NULL)
,('um.Lorem ipsum dol',NULL,NULL)
,('officia dese',NULL,NULL)
,('eu ',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercit',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla par',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fu',NULL,NULL)
,('pariatur. Excepteur sint occaecat cu',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mollit anim id est lab',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in rep',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ',NULL,NULL)
,('amet, consectetur adip',NULL,NULL)
,('nulla pariatu',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt',NULL,NULL)
,('ad minim veniam, quis nostr',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi u',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in rep',NULL,NULL)
,('velit esse cill',NULL,NULL)
,('ipsum dolor ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ali',NULL,NULL)
,('elit, sed',NULL,NULL)
,('occaecat cupidatat non pro',NULL,NULL)
,('in voluptate',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa',NULL,NULL)
,('mollit anim id es',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui of',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore',NULL,NULL)
,('consequat. Duis aute',NULL,NULL)
,('deserunt mo',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('aliqua. Ut enim ad',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit ani',NULL,NULL)
,('aute irure dolor in reprehenderit in voluptate velit esse cillum dolore',NULL,NULL)
,('nisi ut aliquip ex ea commodo con',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',NULL,NULL)
,('ut aliquip ex ea commod',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culp',NULL,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cil',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proi',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse ',NULL,NULL)
,('id est ',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est l',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco laboris ni',NULL,NULL)
,('ut labore et dolore magna ',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut',NULL,NULL)
,('ullamco laboris',NULL,NULL)
,('non',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('velit esse cillum dolore eu fugiat nulla pariatur. Exce',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup',NULL,NULL)
,('occaecat ',NULL,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in voluptat',NULL,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipiscing e',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non p',NULL,NULL)
,('non proident, sunt in culpa qui officia ',NULL,NULL)
,('ipsum dolor sit amet, consectetur a',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia dese',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscin',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco lab',NULL,NULL)
,('elit, s',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exe',NULL,NULL)
,('cupidatat',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est la',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolo',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat c',NULL,NULL)
,('ut labore e',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ea commodo consequat. Duis aute irure dolor in reprehend',NULL,NULL)
,('aute irure dolor in reprehenderit in vo',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequ',NULL,NULL)
,('consequat. Duis aute irure dolor i',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet, conse',NULL,NULL)
,('do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim venia',NULL,NULL)
,('in culpa qui offi',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem',NULL,NULL)
,('cupidatat non',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit an',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pa',NULL,NULL)
,('laboris nisi ut aliquip e',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in volupta',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla',NULL,NULL)
,('aute irure dolor in reprehenderit in voluptate velit esse cillum dolore e',NULL,NULL)
,('elit, sed',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaeca',NULL,NULL)
,('officia deserunt mollit anim id est labor',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sit amet, consectetur adipiscing elit, sed do eiu',NULL,NULL)
,('sit am',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim ven',NULL,NULL)
,('ullamco laboris nisi',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolo',NULL,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, su',NULL,NULL)
,('occaecat cupid',NULL,NULL)
,('minim veniam, quis nostrud',NULL,NULL)
,('ut lab',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolor sit amet, c',NULL,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occae',NULL,NULL)
,('elit, sed do eiusmod tempor incidi',NULL,NULL)
,('sint occaecat cupidatat non ',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatu',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in rep',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dol',NULL,NULL)
,('sit amet, consectetur adipiscing elit, s',NULL,NULL)
,('magna aliqua.',NULL,NULL)
,('cillum dolore eu',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in ',NULL,NULL)
,('Duis au',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercita',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit ani',NULL,NULL)
,('reprehenderit in voluptate velit e',NULL,NULL)
,('mollit anim id est laborum.Lor',NULL,NULL)
,('dolore magna aliqua. Ut',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proid',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor in',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. U',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dol',NULL,NULL)
,('Excepteur ',NULL,NULL)
,('culpa qui officia deserunt mollit anim',NULL,NULL)
,('labore et dolore magna a',NULL,NULL)
,('deserunt mollit anim id est la',NULL,NULL)
,('cupidatat non proident,',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt',NULL,NULL)
,('consequat. Du',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('non proident, sunt in',NULL,NULL)
,('culpa qui officia deserunt mollit anim id ',NULL,NULL)
,('adipiscing elit, sed',NULL,NULL)
,('pariatur. Excepteur sint occaecat cupidat',NULL,NULL)
,('ut labore et dolo',NULL,NULL)
,('proident, sunt in culpa qui officia dese',NULL,NULL)
,('ut al',NULL,NULL)
,('do eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('occaecat cupidatat non pr',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excep',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore e',NULL,NULL)
,('ex ea commodo consequat. Du',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim v',NULL,NULL)
,('irure dolor in repreh',NULL,NULL)
,('pariatur. Excepteur sint occaecat cupidatat no',NULL,NULL)
,('ut aliquip',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laboru',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ip',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliq',NULL,NULL)
,('incididu',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u',NULL,NULL)
,('nulla pariatur. Except',NULL,NULL)
,('pariatur. Excepteur sint occaecat cu',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Dui',NULL,NULL)
,('id es',NULL,NULL)
,('in reprehenderit in voluptate velit e',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est labo',NULL,NULL)
,('velit esse cillum dolore eu fugiat ',NULL,NULL)
,('sit amet, consectetur adipis',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pari',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in v',NULL,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor',NULL,NULL)
,('dolor sit amet, consec',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('qui officia deserunt mollit anim id est laborum',NULL,NULL)
,('mollit anim id est labo',NULL,NULL)
,('magna',NULL,NULL)
,('esse cillum do',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proi',NULL,NULL)
,('ullamco laboris nisi',NULL,NULL)
,('elit, sed do eiusmod tempor ',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id e',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Exce',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('exercitation ulla',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis no',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consec',NULL,NULL)
,('in reprehenderit in voluptate ',NULL,NULL)
,('tempor incididunt ut labore et do',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in r',NULL,NULL)
,('magna aliqua. Ut enim ad m',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamc',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offi',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum do',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit,',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo conseq',NULL,NULL)
,('irure dolor in reprehenderit in',NULL,NULL)
,('aborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ali',NULL,NULL)
,('sed do ei',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor ',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dol',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.L',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercit',NULL,NULL)
,('ea commodo consequat. Duis aute irure dolor',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re',NULL,NULL)
,('ut lab',NULL,NULL)
,('quis nostru',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo con',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp',NULL,NULL)
,('cil',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis au',NULL,NULL)
,('sint occ',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod',NULL,NULL)
,('do eiusmod tempor inci',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse ci',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolo',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ipsum dolor sit amet, consectetur adipiscing ',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no',NULL,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in volupta',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt i',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididun',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veni',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut ali',NULL,NULL)
,('aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo con',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('minim veniam',NULL,NULL)
,('bor',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo c',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do ei',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute i',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequ',NULL,NULL)
,('Duis aute irure dolor in reprehenderi',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute ',NULL,NULL)
,('dolor sit amet, conse',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',NULL,NULL)
,('do ',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut',NULL,NULL)
,('consectetur adipiscing el',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum d',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, con',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusm',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis au',NULL,NULL)
,('velit esse cillum dolore eu fugiat',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('consequat. ',NULL,NULL)
,('Excepteur',NULL,NULL)
,('ut aliquip ex ea commodo consequat. D',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet, conse',NULL,NULL)
,('Ut enim a',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillum d',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consecte',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut la',NULL,NULL)
,('ullamco labor',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, q',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('eu',NULL,NULL)
,('ex ea commodo consequat. ',NULL,NULL)
,('a',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',NULL,NULL)
,('sunt in culpa qui officia deserunt moll',NULL,NULL)
,('occaecat cupidata',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad min',NULL,NULL)
,('elit, sed do e',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupta',NULL,NULL)
,('sed do eiusmod',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('exercitation ullamco laboris nisi ut aliquip ex ea comm',NULL,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, co',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamc',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat ',NULL,NULL)
,('consequat. Duis a',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. ',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et ',NULL,NULL)
,('reprehenderit in voluptate velit esse c',NULL,NULL)
,('anim id es',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sunt in culpa qui officia deserunt mollit anim id est laborum.',NULL,NULL)
,('incididunt ut l',NULL,NULL)
,('et dolo',NULL,NULL)
,('Excepteur sint occaecat cupid',NULL,NULL)
,('veniam, quis nostr',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit an',NULL,NULL)
,('minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip',NULL,NULL)
,('in voluptate velit esse cillum dolore eu f',NULL,NULL)
,('nisi ut aliquip ex ea commo',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco labor',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('tempor incididunt ut labore et ',NULL,NULL)
,('ut aliquip ex ea commodo consequat',NULL,NULL)
,('c',NULL,NULL)
,('elit, s',NULL,NULL)
,('elit, sed do ei',NULL,NULL)
,('sint occaecat cupidatat non proiden',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud',NULL,NULL)
,('dolore eu fugiat n',NULL,NULL)
,('commodo consequat. Duis aute irure do',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidata',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('pariatur. Excepteur sint occaecat cupidatat non',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ma',NULL,NULL)
,('culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolo',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo conse',NULL,NULL)
,('rum.Lorem ipsum dolor sit amet, cons',NULL,NULL)
,('sint ',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidat',NULL,NULL)
,('qui officia deserunt mollit anim id e',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non proident,',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt ',NULL,NULL)
,('sunt in culpa qui of',NULL,NULL)
,('commodo consequat. Duis au',NULL,NULL)
,('incididunt ut labore et dolore ma',NULL,NULL)
,('amet, consectetur adipiscing elit, s',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita',NULL,NULL)
,('tempo',NULL,NULL)
,('aliquip ',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('consequat. Duis aute irure dolor in reprehe',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in repre',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labor',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi u',NULL,NULL)
,('anim id est laborum.Lorem',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolo',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mollit ani',NULL,NULL)
,('deseru',NULL,NULL)
,('pro',NULL,NULL)
,('ipsum dolor sit amet, consect',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ipsum ',NULL,NULL)
,('minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',NULL,NULL)
,('orum.Lorem ipsum dolor sit amet, consectetur adipisc',NULL,NULL)
,('in voluptate velit esse cillum dolo',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate veli',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet,',NULL,NULL)
,('consequat. Duis aute irure do',NULL,NULL)
,('in culpa qui off',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et do',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit e',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('magna aliqu',NULL,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupid',NULL,NULL)
,('ut labor',NULL,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliqu',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt m',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure ',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliq',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deser',NULL,NULL)
,('Ut enim ad minim veniam, quis nostr',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mollit anim id',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa',NULL,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pa',NULL,NULL)
,('ut labore et',NULL,NULL)
,('adipiscing elit, sed do eiusmod te',NULL,NULL)
,('amet, consectetur a',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute iru',NULL,NULL)
,('ut la',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum do',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('amet, consectet',NULL,NULL)
,('dolor in reprehen',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna ',NULL,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolo',NULL,NULL)
,('ex ea commodo consequat. Dui',NULL,NULL)
,('pariatur. Excepteur sint occaecat cupidatat non proi',NULL,NULL)
,('nulla pariatur. Excepteur sint occaec',NULL,NULL)
,('sint occaec',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ad min',NULL,NULL)
,('dolor sit amet, consectetur adipiscing eli',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident,',NULL,NULL)
,('sunt in culpa qui officia deserunt mo',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ven',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui offic',NULL,NULL)
,('l',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipis',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet,',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culp',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore eu fugiat nul',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure do',NULL,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cil',NULL,NULL)
,('ea commodo consequat. Duis aute irur',NULL,NULL)
,('cupidatat non proident,',NULL,NULL)
,('qui officia deserunt m',NULL,NULL)
,('adipiscing elit, sed do eiusmod te',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exe',NULL,NULL)
,('occaecat cupidatat no',NULL,NULL)
,('eli',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('proident, sunt',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit esse ',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod',NULL,NULL)
,('ipsum dolo',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non pro',NULL,NULL)
,('enim ad minim veniam, quis nostrud exercitation ullamc',NULL,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat',NULL,NULL)
,('ex ea commodo consequat. Duis ',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore eu fugiat nulla pariatur. Excepteur',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim ',NULL,NULL)
,('ea commodo consequat. Duis aute irure ',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem i',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolo',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui of',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',NULL,NULL)
,('m.Lorem ipsum dolor sit amet, conse',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('elit, sed do eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in cul',NULL,NULL)
,('adipiscing elit, sed do e',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Ex',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor ',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et do',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur s',NULL,NULL)
,('in voluptate ',NULL,NULL)
,('velit esse cillum dolore eu f',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute ir',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('i',NULL,NULL)
,('dolore eu fugiat nulla',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaeca',NULL,NULL)
,('in reprehenderit',NULL,NULL)
,('sit amet, consectetur adi',NULL,NULL)
,('mollit anim id est la',NULL,NULL)
,('um.Lorem ipsum dolor sit amet, consectetur adipiscing e',NULL,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum do',NULL,NULL)
,('eiusmod tempor i',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sint occaecat cupidatat non proident, sunt in culpa qu',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ',NULL,NULL)
,('consequat. Duis aute irure d',NULL,NULL)
,('do eiusmod tempo',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui officia deser',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in ',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magn',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat cupida',NULL,NULL)
,('est l',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco lab',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Duis aute irure dolor in reprehenderit in voluptate velit esse ci',NULL,NULL)
,('do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim',NULL,NULL)
,('adipiscin',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit an',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nu',NULL,NULL)
,('pariatur. Excepteur sint oc',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. E',NULL,NULL)
,('cupidatat ',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation',NULL,NULL)
,('c',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolore eu fugiat nulla par',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est lab',NULL,NULL)
,('magna aliqua. Ut enim',NULL,NULL)
,('cupidatat non proident, sunt ',NULL,NULL)
,('Duis aute irure dolo',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercita',NULL,NULL)
,('velit esse cillum dolore eu fugiat nu',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('elit, sed do eiusmod tempor incididunt ut labore et dolo',NULL,NULL)
,('in reprehenderit',NULL,NULL)
,('proid',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea com',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exe',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id ',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat ',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi',NULL,NULL)
,('sit amet, consectet',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sunt in culpa qui officia d',NULL,NULL)
,('pari',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offici',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliqu',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in vol',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exer',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui offi',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve',NULL,NULL)
,('ut labore et dolore magna aliqua',NULL,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis a',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('non proident, sunt in culpa qui officia deserunt mollit anim id ',NULL,NULL)
,('au',NULL,NULL)
,('ipsum dol',NULL,NULL)
,('in culpa',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna a',NULL,NULL)
,('in voluptate velit esse cillum',NULL,NULL)
,('adipisci',NULL,NULL)
,('cillum dolore eu fug',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag',NULL,NULL)
,('Excepteur sint occaecat cupid',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non pr',NULL,NULL)
,('aliqua. Ut en',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost',NULL,NULL)
,('ipsum',NULL,NULL)
,('consequat. Duis aute irure do',NULL,NULL)
,('ad minim veniam, quis nostru',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ven',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing e',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat',NULL,NULL)
,('occaecat cupidatat non ',NULL,NULL)
,('ut aliquip ex ea co',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore e',NULL,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse ci',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor',NULL,NULL)
,('e',NULL,NULL)
,('pariatur. Excepteur sint occa',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proide',NULL,NULL)
,('Duis aute irure dolor in reprehe',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et do',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamc',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip e',NULL,NULL)
,('cupidatat non proide',NULL,NULL)
,('laboris nisi u',NULL,NULL)
,('adipiscing elit, sed do ',NULL,NULL)
,('do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint o',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('tempor in',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol',NULL,NULL)
,('Duis aute irure dolor in repreh',NULL,NULL)
,('officia deserunt mollit anim id e',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet,',NULL,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consectetur',NULL,NULL)
,('non proident, sunt in culpa qui ',NULL,NULL)
,('exerci',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse c',NULL,NULL)
,('in voluptate velit esse cillum dolore',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in voluptate ',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occae',NULL,NULL)
,('sit amet, consectetu',NULL,NULL)
,('esse ci',NULL,NULL)
,('est laborum.Lorem ipsum dolor',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, con',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco l',NULL,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('magna a',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolo',NULL,NULL)
,('e',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi',NULL,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur',NULL,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehend',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna ',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mo',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('borum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',NULL,NULL)
,('cillum dolore eu fugiat nulla pariatur. Ex',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ali',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. E',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea com',NULL,NULL)
,('consequat. Duis aute irure dol',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labo',NULL,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('orum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod te',NULL,NULL)
,('sit amet, consect',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut lab',NULL,NULL)
,('enim ad minim veniam, quis nostrud exercita',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud',NULL,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex e',NULL,NULL)
,('aliquip ex ea co',NULL,NULL)
,('a',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('elit, sed do eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore m',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in repreh',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud e',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed ',NULL,NULL)
,('eli',NULL,NULL)
,('cillum dolore eu fu',NULL,NULL)
,('sint occa',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in ',NULL,NULL)
,('incididunt ut lab',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('aliquip ex ea c',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation u',NULL,NULL)
,('ipsum dolo',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo con',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim ',NULL,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetu',NULL,NULL)
,('id est la',NULL,NULL)
,('enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea comm',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerc',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sint occaec',NULL,NULL)
,('in volup',NULL,NULL)
,('consequat. Duis au',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ',NULL,NULL)
,('enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',NULL,NULL)
,('qui',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore ',NULL,NULL)
,('eiusmod',NULL,NULL)
,('qui officia des',NULL,NULL)
,('exercitatio',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ex ea commodo consequat. Duis aute irure dolor ',NULL,NULL)
,('cillum dolore eu fugiat nulla par',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos',NULL,NULL)
,('pariatur. Excepteur sint occaecat ',NULL,NULL)
,('nisi ut aliquip ex',NULL,NULL)
,('nulla pariatur. Excepteur s',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',NULL,NULL)
,('ullamco laboris nisi',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur ',NULL,NULL)
,('orum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim i',NULL,NULL)
,('consequat. Duis aute irure dolor',NULL,NULL)
,('officia deserunt ',NULL,NULL)
,('ut labore et dolore m',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor ',NULL,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ',NULL,NULL)
,('in culpa qui officia deserunt mollit anim id est laborum.Lore',NULL,NULL)
,('m.Lorem ipsum d',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ut labore et dolore magna aliqua',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor i',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ',NULL,NULL)
,('exercitation ullamco laboris nisi ut ali',NULL,NULL)
,('mollit anim id est laboru',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in rep',NULL,NULL)
,('eu fugiat nulla pariatur. Exce',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim',NULL,NULL)
,('eu fugiat nulla pariatur. E',NULL,NULL)
,('incididunt ut labore et dolore ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sint occaecat cupidatat ',NULL,NULL)
,('pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia de',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consect',NULL,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc',NULL,NULL)
,('consequ',NULL,NULL)
,('con',NULL,NULL)
,('cillum dolore eu fugiat null',NULL,NULL)
,('minim veni',NULL,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit',NULL,NULL)
,('quis nostrud exercitation ullamco labor',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('esse cillum dolor',NULL,NULL)
,('in volupt',NULL,NULL)
,('et dolore magna aliqua. Ut ',NULL,NULL)
,('tem',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor',NULL,NULL)
,('Excepteur sint occa',NULL,NULL)
,('voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non ',NULL,NULL)
,('ex ea commodo consequat. D',NULL,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('sint occaecat c',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat',NULL,NULL)
,('anim id est laborum.Lorem ipsum dolor',NULL,NULL)
,('in voluptate velit esse cillum',NULL,NULL)
,('reprehenderit in voluptate veli',NULL,NULL)
,('cillum dolore eu fu',NULL,NULL)
,('consectetur adip',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incid',NULL,NULL)
,('eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini',NULL,NULL)
,('pariatur. Excepteur sint occaecat cupidatat non ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('veniam, quis nostrud',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occa',NULL,NULL)
,('qui officia de',NULL,NULL)
,('mollit anim id est laborum.Lorem ips',NULL,NULL)
,('officia deserunt mollit an',NULL,NULL)
,('ut aliquip ex ',NULL,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit ess',NULL,NULL)
,('incididunt ut labore et dolore magna ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pari',NULL,NULL)
,('adipiscing elit, sed do',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in voluptate velit esse cillum dolore',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,NULL)
,('cup',NULL,NULL)
,('borum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod',NULL,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor ',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur',NULL,NULL)
,('sint occaecat',NULL,NULL)
,('velit esse cill',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('consequat. Duis aute irure dolor in reprehenderit in voluptate ',NULL,NULL)
,('occaeca',NULL,NULL)
,('in ',NULL,NULL)
,('non proident, s',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute iru',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint oc',NULL,NULL)
,('mollit an',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod',NULL,NULL)
,('in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adi',NULL,NULL)
,('aborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('elit, ',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in vo',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi ',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. E',NULL,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. ',NULL,NULL)
,('dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n',NULL,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor s',NULL,NULL)
,('irure dolor in reprehenderit in vo',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris',NULL,NULL)
,('ex ea comm',NULL,NULL)
,('quis nostrud exercitation ullamco laboris n',NULL,NULL)
,('ut aliquip ',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culpa q',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliqu',NULL,NULL)
,('exercita',NULL,NULL)
,('pariatur. Excepteu',NULL,NULL)
,('labore et dolore mag',NULL,NULL)
,('nisi u',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, con',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est labor',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proiden',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis',NULL,NULL)
,('ex ea commodo consequat. Du',NULL,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim ven',NULL,NULL)
,('sed do eiusmod tempor incidi',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla p',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mol',NULL,NULL)
,('ut aliquip ex ea commodo consequat. Duis au',NULL,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',NULL,NULL)
,('Ut enim ad',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercit',NULL,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupida',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo co',NULL,NULL)
,('culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum',NULL,NULL)
,('laborum.Lorem',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non',NULL,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in c',NULL,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis a',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veni',NULL,NULL)
,('qui officia deserunt mollit anim id est ',NULL,NULL)
,('anim id est la',NULL,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo',NULL,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur s',NULL,NULL)
,('nis',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in rep',NULL,NULL)
,('nul',NULL,NULL)
,('et dolore magna aliqua. Ut enim ',NULL,NULL)
,('velit es',NULL,NULL)
,('occaecat c',NULL,NULL)
,('voluptate velit esse cillum dolore eu fugiat nulla pariat',NULL,NULL)
,('consectetur adipis',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',NULL,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',NULL,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo co',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('u',NULL,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate vel',NULL,NULL)
,('non pro',NULL,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur',NULL,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis',NULL,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna al',NULL,NULL)
,('laborum.Lorem ipsum dolor sit',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proiden',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adi',NULL,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad mini',NULL,NULL)
,('dolor in rep',NULL,NULL)
,('v',NULL,NULL)
,('proident, sunt in culpa qui officia d',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserun',NULL,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa ',NULL,NULL)
,('ad minim veniam, quis nostrud e',NULL,NULL)
,('pariatur. Excepteur',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation u',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve',NULL,NULL)
,('proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ip',NULL,NULL)
,('voluptate veli',NULL,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occ',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et d',NULL,NULL)
,('ut labor',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitati',NULL,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ip',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aut',NULL,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea comm',NULL,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud e',NULL,NULL)
,('labore et dolore magna',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',NULL,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut',NULL,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt ',NULL,NULL)
,('sit amet, consectetur adipiscin',NULL,NULL)
,('eu fugiat nulla pariatur. Excepteur sint ',NULL,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('ad',NULL,NULL)
,('tempor incididunt ut labor',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mol',NULL,NULL)
,('aliquip ex ea commodo consequa',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla',NULL,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid',NULL,NULL)
,('ad minim veniam, quis nostrud exercitation ulla',NULL,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita',NULL,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',NULL,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse',NULL,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repre',NULL,NULL)
,('veniam, quis nostrud ',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididun',NULL,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit,',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magn',NULL,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing el',NULL,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate veli',NULL,NULL)
,('deserunt mollit anim id est ',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('culpa qui officia deserunt mollit anim id',NULL,NULL)
,('moll',NULL,NULL)
,('esse cillu',NULL,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsu',NULL,NULL)
,('qui officia deserunt mollit anim id',NULL,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea co',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit',NULL,NULL)
,('tempor incididunt ut labore et dolore ',NULL,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugi',NULL,NULL)
,('Excep',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('incididunt ',NULL,NULL)
,('consectetur adipiscing elit, sed do e',NULL,NULL)
,('tempor incididunt ut la',NULL,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim',NULL,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui ',NULL,NULL)
,('tempor incididun',NULL,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proident',NULL,NULL)
,('o',NULL,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos',NULL,NULL)
,('ullamc',NULL,NULL)
;
INSERT INTO SampleProducts.dbo.Brands (Name,PictureId,[TimeStamp]) VALUES 
('non proident, sunt in culpa qui officia deserunt ',NULL,NULL)
,('occaecat cupidatat non proident, sunt in culp',NULL,NULL)
,('ut aliq',NULL,NULL)
,('et dolore magna aliqua. Ut enim ad minim venia',NULL,NULL)
,('ex ea',NULL,NULL)
,('consequat. Duis aute irure dolor in reprehenderi',NULL,NULL)
,('dolore magna a',NULL,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magn',NULL,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute ir',NULL,NULL)
;