INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('Ut enim ad minim v',NULL,1112,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim ',NULL,1817,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in cu',NULL,1659,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in vol',NULL,1446,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ',NULL,1494,NULL)
,('sint',NULL,1538,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad',NULL,1442,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in volupt',NULL,1991,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt i',NULL,2000,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',NULL,1392,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('pariatur. Excepte',NULL,1267,NULL)
,('est laborum.Lorem ipsum dolor',NULL,1969,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipisci',NULL,1218,NULL)
,('velit esse cillum dolore eu fugiat nulla p',NULL,1312,NULL)
,('anim id est laborum.Lorem ipsum dolor s',NULL,1298,NULL)
,('et dolore magna aliqua',NULL,1788,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidat',NULL,1626,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ',NULL,1580,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet,',NULL,1423,NULL)
,('minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea comm',NULL,1602,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad',NULL,1229,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ul',NULL,1011,NULL)
,('consectetur adipiscing elit, sed do eius',NULL,1707,NULL)
,('sunt',NULL,1528,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veni',NULL,1149,NULL)
,('do',NULL,1264,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis no',NULL,1668,NULL)
,('deserunt mollit anim id est labo',NULL,1697,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaec',NULL,1159,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute iru',NULL,1957,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('borum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor i',NULL,1140,NULL)
,('anim id est laborum.Lorem ipsum dolor sit a',NULL,1792,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d',NULL,1464,NULL)
,('anim id est laborum.Lorem ipsum',NULL,1869,NULL)
,('et dolore magna aliqua. Ut enim',NULL,1192,NULL)
,('laboris nisi ut aliquip ex ea commod',NULL,1185,NULL)
,('sunt in culpa qui officia deserunt mollit',NULL,1416,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo co',NULL,1355,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do ei',NULL,1388,NULL)
,('laboris nisi ut aliquip ex ea comm',NULL,1437,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('ullamco laboris nisi ut aliqu',NULL,1262,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt',NULL,1250,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco labori',NULL,1908,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',NULL,1049,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ',NULL,1523,NULL)
,('i',NULL,1209,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia dese',NULL,1853,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea',NULL,1322,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation',NULL,1179,NULL)
,('ea commodo consequat. Dui',NULL,1802,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari',NULL,1889,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u',NULL,1679,NULL)
,('ullamco laboris nisi ',NULL,1918,NULL)
,('a',NULL,1856,NULL)
,('ut labore et dolore ma',NULL,1978,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillum dol',NULL,1386,NULL)
,('Duis a',NULL,1582,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',NULL,1619,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repre',NULL,1878,NULL)
,('Excepteur sint occaecat cupidatat non p',NULL,1132,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('Duis ',NULL,1936,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat',NULL,1330,NULL)
,('adipiscing elit',NULL,1016,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis',NULL,1340,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occae',NULL,1948,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex',NULL,1347,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat null',NULL,1711,NULL)
,('elit, sed do eiusmod tempor incididunt ut lab',NULL,1596,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor s',NULL,1162,NULL)
,('nisi ut ',NULL,1009,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('qui officia deserunt mo',NULL,1288,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia des',NULL,1729,NULL)
,('sunt in culpa qui officia deserun',NULL,1938,NULL)
,('eu fugiat nulla pariatur. Except',NULL,1923,NULL)
,('consectetur adipiscing elit, sed',NULL,1359,NULL)
,('rum.Lorem ipsum dolo',NULL,1645,NULL)
,('velit ',NULL,1310,NULL)
,('exercitation ul',NULL,1085,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',NULL,1323,NULL)
,('sint occaecat cupi',NULL,1634,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',NULL,1260,NULL)
,('sint occaecat cupidatat non proident,',NULL,1246,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo c',NULL,1223,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor ',NULL,1898,NULL)
,('ullamco laboris nisi ut a',NULL,1101,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit ani',NULL,1644,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ips',NULL,1356,NULL)
,('cupidatat non proide',NULL,1174,NULL)
,('adipiscing elit, sed do eiusmod ',NULL,1824,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc',NULL,1468,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',NULL,1069,NULL)
,('adipiscing elit, sed do eiusmod temp',NULL,1130,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute ',NULL,1789,NULL)
,('ut aliquip ex ea commodo consequat.',NULL,1521,NULL)
,('consectetur adipiscing elit, sed ',NULL,1224,NULL)
,('ut labore et dolore magna aliqua. ',NULL,1420,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut e',NULL,1610,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea com',NULL,1297,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco',NULL,1673,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiu',NULL,1698,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('adipiscing elit, sed do eiusmod tempor incididunt ut labore ',NULL,1702,NULL)
,('voluptate veli',NULL,1992,NULL)
,('non proident, sunt in culpa qui officia deserunt ',NULL,1184,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteu',NULL,1865,NULL)
,('et dolore magna aliqua. Ut enim ad',NULL,1696,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, c',NULL,1639,NULL)
,('elit, sed do eiusmod tempor incididunt ut labo',NULL,1783,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et d',NULL,1014,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet,',NULL,1906,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ',NULL,1652,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('in reprehenderit in voluptat',NULL,1255,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius',NULL,1405,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag',NULL,1404,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',NULL,1567,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis no',NULL,1337,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proide',NULL,1153,NULL)
,('incididunt ut labore et dolore mag',NULL,1114,NULL)
,('minim veniam, quis nostrud exerc',NULL,1658,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu',NULL,1896,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fug',NULL,1275,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('in voluptate velit esse cillum dolore eu',NULL,1147,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. U',NULL,1102,NULL)
,('qui officia deserunt mo',NULL,1242,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consecte',NULL,1168,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',NULL,1466,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',NULL,1478,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet,',NULL,1670,NULL)
,('aliqua. Ut enim ad minim veniam',NULL,1950,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',NULL,1384,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum',NULL,1458,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('laboris nisi ut aliquip ex ea commodo c',NULL,1829,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proid',NULL,1040,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit ani',NULL,1937,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor',NULL,1467,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, c',NULL,1560,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure do',NULL,1289,NULL)
,('mollit anim id',NULL,1782,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisci',NULL,1692,NULL)
,('ut l',NULL,1395,NULL)
,('consequat. Duis aute i',NULL,1243,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('occ',NULL,1507,NULL)
,('minim veniam, quis nostrud exercitation ullamco l',NULL,1877,NULL)
,('veniam, quis nostrud exercitation ullamco laboris',NULL,1820,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in repr',NULL,1861,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',NULL,1897,NULL)
,('sint occaecat cupidatat non',NULL,1604,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate',NULL,1703,NULL)
,('Duis aute irur',NULL,1763,NULL)
,('et dolore magna aliqua. ',NULL,1220,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat ',NULL,1731,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('ut aliquip ex ea commodo conse',NULL,1630,NULL)
,('.Lorem ipsum dolor sit',NULL,1526,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupi',NULL,1261,NULL)
,('Excepteur sint occ',NULL,1732,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugia',NULL,1300,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',NULL,1830,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ips',NULL,1277,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit',NULL,1768,NULL)
,('in reprehenderit in voluptate velit esse cillum d',NULL,1911,NULL)
,('dolor in reprehenderit in ',NULL,1514,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('Duis aute irure dolor in reprehenderit in voluptate',NULL,1030,NULL)
,('consequat. Du',NULL,1863,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit e',NULL,1960,NULL)
,('occaecat cupidatat non pro',NULL,1433,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu',NULL,1595,NULL)
,('c',NULL,1852,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',NULL,1671,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,',NULL,1357,NULL)
,('nisi ut aliqu',NULL,1309,NULL)
,('qui officia des',NULL,1594,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim i',NULL,1959,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mi',NULL,1313,NULL)
,('sunt in culpa',NULL,1924,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat null',NULL,1084,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dol',NULL,1994,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fug',NULL,1137,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsu',NULL,1076,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui officia deser',NULL,1252,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, conse',NULL,1850,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim v',NULL,1519,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillu',NULL,1885,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet,',1178,1726,NULL)
,('ad minim veniam, quis nostrud exercitation ullam',1087,1839,NULL)
,('sint occaecat cupid',1091,1825,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim venia',1029,1965,NULL)
,('culpa qui officia deserunt mollit an',1055,1038,NULL)
,('id',1173,1815,NULL)
,('magna aliqua. Ut enim ad',1169,1995,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad min',1005,1290,NULL)
,('et dolore magna aliqua. Ut enim ad minim veni',1178,1344,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat n',1106,1435,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in rep',1165,1872,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit e',1149,1240,NULL)
,('exercitation ullam',1103,1203,NULL)
,('ut labore et dolore magna aliqua.',1108,1138,NULL)
,('fugiat nulla pariatur. Excepteur sint occaec',1027,1751,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna a',1042,1956,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo c',1052,1750,NULL)
,('ex ea commodo consequat. Dui',1002,1327,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in v',1071,1700,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('Duis aute irure dolor in r',1090,1234,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu ',1005,1752,NULL)
,('culpa qui officia deserunt mollit anim id',1193,1710,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupta',1197,1048,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ',1132,1728,NULL)
,('anim id est labo',1015,1888,NULL)
,('consequat. Du',1027,1274,NULL)
,('labori',1085,1998,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu',1010,1427,NULL)
,('deserunt mol',1077,1819,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui',1163,1842,NULL)
,('Ut enim ad minim veniam',1039,1812,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur s',1075,1902,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui off',1099,1765,NULL)
,('orum.Lorem ipsum dol',1039,1769,NULL)
,('orum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun',1182,1029,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim',1032,1760,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exercit',1053,1541,NULL)
,('minim veniam, quis nostrud exercitation ullamco laboris nisi ut a',1176,1127,NULL)
,('et dolore ma',1170,1444,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exer',1169,1689,NULL)
,('ipsum dolor sit amet, consectetur a',1006,1120,NULL)
,('non proide',1177,1919,NULL)
,('Ut enim ad minim veniam, quis nostr',1088,1044,NULL)
,('elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad m',1181,1705,NULL)
,('laboris nisi ut aliquip ex ea commodo conse',1124,1980,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut a',1007,1508,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem',1051,1797,NULL)
,('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit a',1119,1631,NULL)
,('enim ad minim veniam, quis nostrud exercitation ullamco labo',1139,1248,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('occaecat cupidatat n',1040,1857,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',1121,1674,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exe',1117,1221,NULL)
,('mollit anim id est laborum.Lorem',1104,1831,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in ',1062,1100,NULL)
,('i',1038,1539,NULL)
,('aute i',1152,1964,NULL)
,('dolor in reprehenderit in vol',1050,1054,NULL)
,('adi',1182,1034,NULL)
,('sint occaeca',1063,1348,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('elit, sed do',1071,1301,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consec',1134,1953,NULL)
,('non proident, s',1200,1460,NULL)
,('exercitation ullamco laboris n',1031,1614,NULL)
,('d',1007,1502,NULL)
,('dolor sit amet,',1018,1922,NULL)
,('sint occaecat',1149,1362,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in v',1043,1028,NULL)
,('aute irure dolor in reprehenderit i',1012,1533,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ulla',1144,1643,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('amet, consectetur adipis',1033,1666,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur si',1168,1105,NULL)
,('ad minim veniam, quis',1159,1609,NULL)
,('enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo',1200,1744,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo conseq',1045,1822,NULL)
,('ipsum dolor si',1045,1685,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat',1115,1364,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',1187,1905,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat',1152,1848,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur',1176,1021,NULL)
;
INSERT INTO SampleProducts.dbo.Categories (Name,ParentId,PictureId,[TimeStamp]) VALUES 
('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea',1029,1962,NULL)
,('mag',1141,1772,NULL)
,('eiusmod tempor',1082,1489,NULL)
;