INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('quis','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint o','quis nostrud exercitation ullamco laboris nisi u',9564,672440128.00,957,NULL)
,('ullamco','sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qui','moll',22336,571785408.33,428,NULL)
,('ipsum dolor sit amet, conse','sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum','consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat ',25446,373848896.52,338,NULL)
,('offic','officia deserunt molli','aliquip ex ea commodo consequat. Duis au',32615,903663680.80,256,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in cu','Excepteur sint occaeca','exercitatio',18354,412744064.22,695,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim a','nostrud exe','do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostru',15296,1806602496.38,96,NULL)
,('mollit anim id est laborum.Lorem','exercitation ullamco laboris nisi ut aliquip ex ea commodo consequ','aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fug',14812,141311920.38,339,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in r','al','ad minim veniam, quis no',1109,1565051392.62,692,NULL)
,('do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad m','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod t','amet, consectetur adipiscing elit',18354,197639696.46,90,NULL)
,('quis nostrud exercitation ullamco laboris nis','laboris nisi ut aliquip ex ea commodo consequat','ullamco laboris nisi ut ',17069,1475377920.41,110,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit a','occaecat cupi','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc',14202,1147535360.59,584,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat','anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos',16894,1199328128.13,66,NULL)
,('adi','ad minim venia','sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru',1599,533503328.85,304,NULL)
,('ullamco laboris nisi ut aliqu','commodo consequat. Duis aute irure dolor in rep','sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ',30389,1245412224.13,892,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut l','ullamco labori','non proident, sun',4260,1412901248.17,907,NULL)
,('ullamco laboris ni','Duis aute irure do','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ',21042,1096621696.21,43,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolo','eiusmod tempor incididunt ut labore et dolore magna al','nulla pariatur. Excepteur sint occaecat cupidatat non proiden',4450,1025739136.33,238,NULL)
,('in voluptate velit esse cillum ','velit esse cillum dolore eu fugiat nulla p','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum',25060,1488445440.90,287,NULL)
,('sint occaecat ','esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup','nulla pariatur. Excepteur sint occaecat cupidatat no',30874,393824000.32,44,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor i','reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint ','cupidatat non proident, sunt in c',19833,77890912.41,793,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('fugiat nulla pariatur. Excepteur sint occae','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non pro','esse cillum dolore eu fugiat nulla pariatur. Excepteur',19986,671502528.54,221,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullam','amet, consec','pariatur. E',28537,1665061888.10,305,NULL)
,('consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nu','ut labore et dolore magna aliqua. U','qui officia deserunt mollit anim id est laborum.Lorem ipsum d',3359,1783469184.18,754,NULL)
,('incidi','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit','exercit',1722,1517559680.18,667,NULL)
,('esse cillu','eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat','in voluptate velit esse cillum dolore eu fugi',472,1735244416.39,362,NULL)
,('qui offici','aute irure dolor in reprehenderit in volupta','magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco ',26850,787245824.90,345,NULL)
,('ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ali','incididunt ut labore et dolore magna aliq','nulla pariatur. Excepteur sint occaecat cupidatat non proident',25739,1151059584.85,484,NULL)
,('aborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor','aborum.L','Excepteur sint occaecat cupidatat non proident, sunt in culpa',13915,890742464.35,218,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehen','do eiusmod tempor incididunt ut labore e','sint occaecat cupidatat non proident, sun',14456,753095744.67,610,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proi','ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum d','ipsum dolor sit amet, consectetur adipiscing elit, sed do e',28163,1400295040.14,589,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('ipsum dolor sit amet, consectetur adipiscing elit, sed d','cupidatat non proident, sunt in culpa qui officia deserunt','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut',32378,1202821376.15,765,NULL)
,('do eiusmod tempor incididunt u','al','ea commodo consequat. Duis aute irure dolor in repr',11968,170320224.70,262,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, q','esse cill','tempor inci',28213,1772891904.12,310,NULL)
,('cillum dolore eu fugiat nulla pariatur. Excepteur sint occaec','eiusmod tempor incididunt ut l','a',18916,1742168320.17,259,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidat','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excep','labore et dolore magna aliqua. Ut enim ad minim veniam, quis',31691,1131474304.99,332,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in ','aliquip ex ea commodo cons',2295,1480163200.70,852,NULL)
,('nulla','officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectet','ullamco laboris nisi ut aliquip ex ea c',1542,1314544896.78,185,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute','cupidatat non proident, sunt in culpa qui offici','fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in c',29420,1173769472.86,785,NULL)
,('consequat','ullamco laboris nisi ut aliquip ex','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup',3874,1593127808.40,770,NULL)
,('consequat. Duis aute irure dolor in reprehen','id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing eli','.Lorem ipsum dolor sit amet, consectetur adipis',16123,54674144.89,283,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('reprehenderit in voluptate velit es','commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu f','in repreh',18312,1310001536.81,994,NULL)
,('aliqua. Ut enim ad minim veniam, quis ','sint ','Excepteur sint occaecat cupidatat non proident, sunt in culpa qu',4711,931977152.80,858,NULL)
,('Duis au','exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re','ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate ve',6641,85485928.96,153,NULL)
,('incididunt ut labore et dolo','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Except','anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp',6713,901861632.24,690,NULL)
,('sint occaecat cupidatat non proident, sunt in','ve','in voluptate velit esse cillum d',18369,1515732224.37,348,NULL)
,('Duis aute irure','pariatur. Excepteur','adipiscing elit, sed do eiusmod tempor incididunt ut l',31375,970334784.85,968,NULL)
,('ut labore et dolor','occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru','adipiscing eli',8655,502956832.55,751,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, se','veniam, quis','nulla pariatur. Excepteur sint occa',31835,399870016.39,189,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ','anim id est laborum.Lorem ips','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',13916,227499440.29,976,NULL)
,('proident, sunt in culpa ','cupidatat non proident, sunt in culp','dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull',19364,832415872.30,711,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('ullamco laboris nisi ut aliquip ','ea commodo conseq','Except',19215,1718570624.54,476,NULL)
,('velit esse cillum dolore eu fugiat nulla pariat','dolore','ullamco l',22085,1446312576.40,178,NULL)
,('quis nostrud exercitation','aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi','nostrud exercitation ullamco laboris nisi',19312,1451312000.32,676,NULL)
,('cupidatat non proident, sunt in cul','ullamco laboris nisi ut aliquip ex ea comm','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur',23673,773314880.21,882,NULL)
,('aute ','offici','sunt in culpa',28329,1591237248.60,838,NULL)
,('nostrud exercitation ullamco laboris n','exercitation ullamco laboris nisi u','velit esse cillum dolore eu ',8526,156616064.86,140,NULL)
,('eu fugiat nulla ','esse cillu','ea commodo consequat. Duis aute iru',9455,1267981952.70,149,NULL)
,('officia deserunt mollit anim id est laborum.Lorem ip','eu fugiat nulla pariatur. ','irure dolor in reprehenderi',23946,1045696192.56,228,NULL)
,('deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc','et dolore magna aliqua. Ut enim ad minim','amet, consectetur adipiscin',17661,111841744.13,190,NULL)
,('voluptate velit esse','quis nostrud exercitation ulla','sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ',18985,459097568.43,8,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('proident, sunt in culpa qui officia deserunt mollit anim id es','m','tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostr',11869,374350336.40,276,NULL)
,('deserunt mollit','ut labore et dolore magna aliqua. Ut','officia d',25640,158679936.31,963,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehen','elit, sed do eiusmod tempor incididunt u','commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse',11055,826725312.46,870,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad min','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur','tempor incididunt ut labore et dolore magn',31077,888108608.11,807,NULL)
,('ut labore et do','esse cillum dolore eu fugiat nulla pariatur. Except','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum d',4754,579926528.70,630,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam,','ad minim veniam, ','consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor',7091,924536960.54,925,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor s','ut labore et dolore magna aliqua. Ut enim ad minim ven','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupi',32603,1783421952.97,103,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore','Excepteur sint',6673,1543526912.40,322,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla pariatur.','veniam, quis nostrud exercitation ullamco laboris nisi','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proiden',28535,1607041536.82,849,NULL)
,('veniam, quis nostrud exercitation ulla','aute irure dolor in reprehenderit in voluptate velit esse cillum do','sint ',30530,460242048.43,213,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('dolor sit amet, consectetur adipiscing elit, sed do eiusm','mollit anim id est laborum.Lorem','dolor sit',10479,1449149056.46,148,NULL)
,('non proident, sunt in culpa qui officia deserunt ','incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exe','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, conse',12091,961650304.26,391,NULL)
,('quis ','irure dolor in reprehenderit in voluptate velit esse cillum dolore','quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis a',17567,770364032.32,432,NULL)
,('ex ea commodo consequat. Duis aute irure dolor in reprehende','laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occa',8541,160284384.55,673,NULL)
,('dolor in reprehenderit in voluptate ','non proident, sunt in culpa qui','aute irure dolor in reprehenderit in',32628,1706854144.98,919,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum ','aute irure dolor in reprehenderit in v','amet, consectetur adipis',17164,828691008.28,644,NULL)
,('voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint oc','ut labore et d','tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim v',30562,397671360.64,802,NULL)
,('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, s','velit esse cillum dolore eu fugiat nulla pariat','qui officia deserunt mollit anim i',24561,918307968.17,974,NULL)
,('ullamco laboris n','tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim v','consectetur adipiscing elit, sed do ei',24612,945965632.54,980,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt u','laboris nisi ut aliquip ex ea commodo consequat. Duis aute i','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut a',21773,1827387648.38,273,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco l','dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non','sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',2589,886004416.84,961,NULL)
,('esse cillum dolore eu fugiat nulla ','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur ','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ',5380,682506944.84,848,NULL)
,('ut al','occaecat cupidatat non proident, sun','quis nostrud ex',21571,1283640960.85,707,NULL)
,('pariatur. Excep','ea commodo consequat. Duis aute irure dol','Excepteur sint occaecat cupidatat non proident, sunt in culpa',2680,1351645696.64,370,NULL)
,('voluptate velit ','incididunt ut labore e','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',5519,1319081728.24,448,NULL)
,('velit esse cillum ','officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit','culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',22219,928369536.20,271,NULL)
,('sed do eiusmod tempor incididunt ut labore et dolore magna ali','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation','exercitation ullamco laboris nisi ut aliquip ex ea commodo ',32209,973344896.66,7,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun','sunt in cu','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ull',8169,1310967808.50,73,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure do','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no','nulla par',6751,817254208.51,850,NULL)
,('ut aliquip ex ea commodo consequa','cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat','officia deserunt mollit anim id est',23182,647936512.36,947,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('ex ea commodo consequat. Duis aute irure dolor in','officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing','esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, s',14646,1738209664.94,878,NULL)
,('veniam, quis nostrud exercitation ullamco labo','veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea ','Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqu',26021,1516543488.86,766,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conseq','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit','irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariat',28478,1285341952.39,835,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim','aute irure dolor in reprehenderit in volupt','laboris nisi ut aliquip ex ea commodo consequat.',4849,551717760.75,188,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerci','aliq','nisi ut aliquip ex ea commodo consequat. Dui',25618,937556928.24,12,NULL)
,('occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum','deserunt mollit anim id est laborum.Lorem ipsum dol','adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad min',25499,1072556672.66,464,NULL)
,('nisi ','consect','veniam, quis nostrud exercitation ullamco laboris ',27459,1025104704.27,174,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipi','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dol','tempor incididunt ut labore et dolore magna aliqua. Ut e',15561,1713725312.81,357,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqui','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla','magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ni',5663,1269592832.27,752,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et d','cupidat','cupidatat non proident, sunt in culpa qui of',17996,1388084480.81,181,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('non ','pariatur. Excepteur sint occaecat cupida','dolore eu fugiat nu',11876,1137724032.10,972,NULL)
,('dolore magna aliqua. Ut enim ad minim veniam, qu','in voluptate velit esse cillum dolore eu fugiat nulla pariatu','elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad',25931,1597481088.32,894,NULL)
,('dolor in reprehenderit in voluptate velit esse','in reprehenderit in voluptate velit esse cillum dolore eu fugiat ','adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',30690,785083392.40,627,NULL)
,('aute irure dolor in reprehenderit in voluptate velit','adipiscin','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ',16802,1870549120.51,851,NULL)
,('in voluptate velit esse cill','enim ad minim veniam, quis nostrud exercitati','aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugi',25179,407758272.30,385,NULL)
,('elit, sed do eius','elit, sed do eiusmod tempor incididunt ','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit',23840,1273648256.80,698,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate ','Excepteur sint occaecat cupidatat non proide','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in v',16508,810271040.47,813,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qu','elit, sed do eiusmo','aborum.Lorem ipsum dolor sit',9347,1747940224.50,567,NULL)
,('Ut enim ad minim','amet, consectetur adipiscing elit','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerci',23146,1593270016.91,672,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillu','Excepteur sint occaecat cupidatat non proident, sun','in voluptate velit esse cillum dolore eu',18891,1397856256.88,837,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('dolor sit am','laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inci','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore e',17058,1057469632.93,78,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea com','q','deserunt molli',17926,811444672.26,801,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt m','Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut','id est laborum.Lorem',6735,246113056.14,932,NULL)
,('sit amet, ','in reprehenderit in voluptate velit esse cillum dolore eu fu','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volupt',13251,433750336.13,457,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam,','adipiscing elit, sed do eiusmod tempor incididunt ut labore e','non proident, sunt in culpa qui officia deserunt mo',29972,1282764800.54,553,NULL)
,('amet, conse','ullamco','in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor',9181,606862144.34,115,NULL)
,('laboris nisi ut aliq','magna aliqua. Ut enim ad minim','sed do eiusmod tempor incididunt ut labore et dolor',10520,165586768.92,341,NULL)
,('mollit anim id est laborum.Lorem ipsum dolor','tempor incididunt ut labore et dolore ma','adipiscing elit,',6954,174315200.72,247,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita','adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit i',9071,1596371584.28,280,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cill','incididunt ut labore et dolore magna aliqua. Ut enim ad minim v','aliqua. Ut enim ad minim veniam, quis nostrud exercitation u',27551,384726336.48,19,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('proident, sunt in culpa','veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conse','ipsum dolor sit amet, consectetur adipiscing elit, sed do eius',13033,1748155136.30,926,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehend','proident, sunt in ','in voluptate velit esse cillum dolore eu fugiat nulla par',26259,1588444928.73,637,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerci','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor','dolore eu fugi',4235,857658944.68,450,NULL)
,('proident, sunt in culpa qui officia d','Duis aute irure dolor in reprehenderit in voluptate ve','dolore eu fugiat nulla pariatur. Exce',3110,1528126976.78,200,NULL)
,('dolore eu fugiat nulla','exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute ir','commodo consequat. Duis aute irure',31382,895406848.25,9,NULL)
,('nostrud exercitation ullamco laboris nisi','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis no','dolore magna a',19036,530102080.57,853,NULL)
,('culpa qui officia deserunt mollit anim id est laborum.Lorem i','anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor i','culpa qui officia dese',30668,1371351680.70,281,NULL)
,('in reprehenderit in voluptate velit esse cillum dolor','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi u','ut labore et dolore magna a',3446,1246353152.33,715,NULL)
,('m','laborum.Lorem ipsum dolor sit amet, consectetur adipiscing eli','eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim',29648,481590944.91,800,NULL)
,('ullamco labor','in culpa qui officia deserunt mollit anim id est laborum.Lorem','qui officia deserunt mollit anim id est laborum.',28783,585442944.56,261,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('reprehenderit in voluptate velit esse cillum dolore eu fugiat ','in culpa qui ','ulla',21284,446703392.59,456,NULL)
,('velit esse cillum dolore eu fugi','rum','sit amet, consectetur adipiscing el',8215,708627840.26,699,NULL)
,('Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt molli','proident, sunt in culpa qui officia dese','incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exer',5640,1323988608.24,559,NULL)
,('consectetur adipiscing elit,','consequat. Duis aute','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d',31422,207940496.29,424,NULL)
,('in reprehenderit in voluptate veli','nisi ut aliquip ex ea co','dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excep',25417,1087888256.60,494,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo','nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia d','laboris nisi ut aliquip ex ea commodo consequat. Duis ',24026,1859970688.56,532,NULL)
,('tempor incididunt ','in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum d','Duis aute irure',10991,547316992.58,834,NULL)
,('Excepteur sint occaeca','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiu','sint occaecat cupidatat non proident, sunt in culpa qui officia dese',32164,1822716032.58,517,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipis','in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit',24414,1717505280.86,204,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud ex','est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, s','anim id est laborum.Lorem ipsum dolor sit amet,',14483,1676508032.96,906,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea co','Excepteur sint occae','aliqua. Ut enim ad minim veniam, quis ',22318,51815816.55,585,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dol','mollit ani',11452,1649602432.48,533,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru','magna aliqua. Ut eni',7288,736955968.58,427,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam,','Excepteur sint','dolor in reprehenderit in voluptate velit esse cillum dolore eu',30860,75513120.55,70,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis ','ut labore et dol','tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ',1116,1431847296.73,845,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsu','eu fugiat nulla pariatur. Excepteur sint occaecat c',11788,694219200.55,708,NULL)
,('anim id est laboru','ut labore et dolore ','Excepteur sint occaecat cupidatat non proid',24389,301380960.40,198,NULL)
,('in repre','non proident, sunt ','nisi ut aliquip ex ea commodo consequat. Duis aute i',28341,1414140032.32,1000,NULL)
,('mollit anim id ','ut labore','nulla pariatur. Excepteur sint occaecat cupidatat non proident, s',16164,291618240.32,129,NULL)
,('irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat null','sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag','ut aliquip ex ea commodo consequat. Duis aute irure dolor in repr',27789,115341320.57,205,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('occaecat cupidatat non proident','Excepteur sint occaecat cupidat','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, cons',18549,542589248.51,816,NULL)
,('adipiscing elit, sed do eiusmod tempor','enim ad minim veniam, quis nostrud exercitation ullamco laboris ','Excepteur si',27685,1810428416.82,746,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe','fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa ',32194,212727696.42,683,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',3083,888088512.39,410,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mol','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehend',17792,1739959424.84,951,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullam','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum do','exercitation ullamco laboris nisi ut aliquip ex ea co',10077,594450304.40,983,NULL)
,('amet, con','velit esse','in voluptate velit esse cillum',32599,73848096.69,564,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim','Excepteur sint occaecat cupidatat non proiden','magna aliqua. U',6993,82704928.74,138,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in re','cillum dolo','esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occa',3888,863417728.88,352,NULL)
,('fugiat','dolor sit amet, consectetur adipiscing elit, sed do e','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing',23882,1146469760.39,139,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut eni','in voluptate velit e','magna aliqua',26420,1293663744.58,617,NULL)
,('dolo','veniam, quis nostrud exercitati','consequat. Duis aute irure dol',6499,325664288.49,873,NULL)
,('do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ','dolor sit amet, consectet','anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed',19537,1835522816.15,159,NULL)
,('esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt','id est laborum.Lorem ipsum dolor sit amet, consectetur adi','ex ea commodo consequat. D',14051,80238856.80,482,NULL)
,('nulla pariatur. Excepteur sint occaecat c','anim id est laborum.Lorem','Ut enim ad minim ven',28893,778334080.56,171,NULL)
,('nulla pariatur. Exce','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit e','exercitation ullamco laboris nisi ut aliquip',26147,1036171392.97,50,NULL)
,('eu fugia','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repreh','ut aliquip ex ea comm',3407,1338231040.55,463,NULL)
,('veniam, quis no','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d','nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui',23061,56573628.96,392,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in','Duis aute irur','aliqua. Ut enim ad minim veniam, quis nostrud exercita',20934,476802720.41,32,NULL)
,('pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui off','tempor incididunt ut labore et dolore m','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occa',27735,791257344.68,769,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('laboris nisi ut aliquip ex ea commo','consequa','aliqua. Ut enim ad minim veniam, quis nostrud exercita',4037,570848448.79,826,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla','veniam, quis nostrud exercitation ul','qui officia des',24374,25255266.10,836,NULL)
,('aute irur','cupi','irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugia',24903,1806527616.28,603,NULL)
,('aliquip ex ea commodo consequat. ','eu fugiat nulla pariatur.','aliqua. Ut enim ad minim veniam, quis nostrud exercit',30660,569274816.92,827,NULL)
,('occaecat cup','nisi ut aliquip ex ea commodo consequa','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ',822,6217540.10,250,NULL)
,('qui officia deserunt','pariatur. Excepteur sint occaecat cupidatat non proident, s','non proident, ',16086,964438912.36,116,NULL)
,('tempor incididunt ut labore et dolor','Duis aute irure','eli',14047,594254720.15,745,NULL)
,('deserunt mollit anim id est laborum.Lorem','dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui ','ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolo',6121,727470976.69,524,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit,','nostrud exercitation u','velit esse cillum dolore eu fugiat nulla pariatur. Excepte',17515,94993728.46,317,NULL)
,('dolor sit amet, consectetur adipiscing elit','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugia','aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla paria',31216,330806976.20,418,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('ullamco laboris nisi ut aliquip ex','amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqu','laborum.Lorem ips',20384,1690394112.66,619,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit ','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in ','ad minim veniam, quis nostrud exercitati',10258,1725532160.78,14,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu','ad minim veniam, quis nostrud exercitation ull','eu',10970,357879136.26,157,NULL)
,('laboris nisi ut aliquip ex ea commodo conseq','aute irure dolor in reprehenderit in voluptate velit ess','aliqua. Ut ',15318,1691101440.98,780,NULL)
,('ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit es','aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla par','dolore eu fugiat ',34,1833692672.17,905,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute iru','non proident, sunt in culpa qui officia deserunt mo','in voluptate velit ',11321,1132228608.12,222,NULL)
,('tempor incididunt ut labore e','exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure ','amet, consectetur adipis',6344,969090176.41,985,NULL)
,('dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nu','quis nostrud exercitation ullamco laboris nis','laboris nisi',2800,681165632.35,632,NULL)
,('in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sin','qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, con',23071,574792832.10,381,NULL)
,('adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad m','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipis','in reprehenderit in',32738,864670720.16,413,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute','voluptate velit esse cillum','voluptate velit esse cillum dolore eu f',14881,1447182976.58,551,NULL)
,('in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur a','amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut','Duis aute ir',30991,1797558912.45,697,NULL)
,('nisi ut aliquip ex ea comm','consectetur adipiscing ','voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint oc',4501,1369913600.68,374,NULL)
,('occaecat cupidatat non proid','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisc','magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat',741,719484480.64,71,NULL)
,('voluptate velit esse cillu','laboris nisi ut aliquip ex ea commodo consequat.','Ut enim ad minim veniam, quis nostrud exercitation ull',3894,1790197760.68,183,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exer','reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occa','exe',18277,896782656.40,510,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt ','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteu','elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veni',31584,552589568.26,257,NULL)
,('aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nul','et dolore magna aliqua. Ut enim ad minim veni','ullamco laboris nisi ut ',2883,1308671488.13,336,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exercit','ad','in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excep',20611,901487808.75,548,NULL)
,('Duis aute irure','cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor s',9064,1637423616.21,991,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('consectetur ','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in r','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris ',20450,1590126336.72,881,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol','Excepteur sint occaecat cupidatat','aute irure dolor in reprehenderit in voluptate velit esse cillum dolor',2273,523793696.99,92,NULL)
,('vol','off','sint occaecat cupidatat non proident, sunt in cul',31358,1069012416.20,360,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ip','mollit anim id est la','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat no',17571,1152418688.50,25,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectetur adip','ullamco laboris nisi ut aliquip ex ea commodo co','voluptate velit esse cillum dolore eu fugiat nulla paria',23876,566407232.80,522,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserun','incididunt ut labore et dolore magna aliqua. Ut','sint occaecat cupidatat non proident',20720,1073743104.57,452,NULL)
,('ad minim veniam, quis nostrud ex','tempor incididunt ut labore et dolor','dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui',15704,834726784.93,615,NULL)
,('aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamc','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur','et dolore magna',10090,1785654144.95,255,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non','eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ven','adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim a',9292,1457260544.68,405,NULL)
,('aute irure dolor in reprehenderit in voluptate vel','enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliq','ullamco laboris nisi ut aliquip ex ea ',2858,757351552.50,728,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('commodo conseq','velit esse cillum dolore eu fugiat nulla pariatur. Except','Excepteur sint occaecat cupidatat non proident, sunt in ',4908,1543640704.62,210,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore','do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostr','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si',10603,115699600.54,86,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate veli','dolor sit amet','sit amet, consectetur adipiscin',16662,1852070016.38,330,NULL)
,('est l','ex ea commodo consequat. Duis aute','ullamco laboris nisi ut aliquip ex ea commo',6803,593550912.80,921,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolo','Excepteur sint occaecat cupidatat','sunt in culpa qui officia deserunt mol',31088,183221760.52,293,NULL)
,('cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lore','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in volup','ex',11560,528151648.29,512,NULL)
,('sit amet, consectetur ','occaecat cupidatat non proident, sunt in culpa qui offi','eiusmod t',32014,137451936.38,500,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proi','nos','incididunt ut labore et dolore magna aliqua. U',8446,1625698048.73,407,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magn','nulla pariatur. Excepteur s','eiusmod tempor incididunt ut labore et dolore mag',3931,6989424.26,492,NULL)
,('exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in r','mollit','ad minim veniam, qui',21621,1078824192.91,811,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut','ex ea commodo consequat. Duis aute i','ut aliquip ex ea commodo con',7735,1245474304.18,700,NULL)
,('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui off','eiusmod tempor incididunt ut labore et d','amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et',13934,31040206.39,897,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur ','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis ','incididunt ut labore et ',15377,1680754816.87,433,NULL)
,('proident, sunt in culpa qui officia deserunt','velit esse cillum dolore eu fugiat nu','Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ',19560,210230000.40,792,NULL)
,('non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dol','laboris nis','ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe',23700,591960896.70,430,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ','exercitation ullamco laboris nisi ut aliqu','magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco ',29264,284012832.73,431,NULL)
,('Duis aute irure dolor in reprehenderit in voluptat','incididunt ut labore et dolore magna aliqua. Ut enim ad minim veni','sint occaecat cupidatat non proident',25377,1356637824.64,390,NULL)
,('Ut enim ad minim ve','sunt in culpa qui officia deserunt mollit anim id est laborum.','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am',20663,1170584832.34,251,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ma','non proident, sunt in culpa qui officia deserunt mollit anim id est','.',33,878492096.20,82,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis n','sed do eiusmod tempor incididunt ut labore et do','in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum',10123,208830720.67,368,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo c','id est laborum.Lor','commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit ',1303,1644037248.86,59,NULL)
,('sint occaecat cupidatat non proident, sunt in cul','sit amet, consectetur adipi','non proident, sunt in culpa qui officia deserunt mollit anim id est ',32634,215865184.18,987,NULL)
,('cillum dolore eu fugiat nulla pariatur. E','officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipi','et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nis',11703,1850168832.20,828,NULL)
,('nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo c','sint occaecat cupidatat non p','anim id est lab',28211,781306560.77,459,NULL)
,('velit esse ','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupida',803,396068480.32,621,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe','do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad ','eu fugiat nulla pariatur. Excepteur sint occaecat ',8897,347287008.97,84,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qui','in culpa qui offic','ullamco laboris nisi ut aliquip ex ea commodo consequ',20730,467971264.38,744,NULL)
,('exercitation ullamco laboris nisi ut a','voluptate veli','non proident, sunt in culpa qu',3290,1293636736.50,871,NULL)
,('eu fugiat nulla pariatur. Excepteur sint occaecat cupi','ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate v','occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit',14410,191507536.30,993,NULL)
,('dolor sit amet, consectetur adipiscing elit, sed do eiusmod te','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco lab','non proident, sunt in cu',7595,1407330304.10,988,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia de','deserunt molli','ut lab',14097,1066682624.82,135,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu','cupidatat non proi',31166,577503744.13,775,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure d','nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Dui','nisi ut aliqui',11243,290528992.88,158,NULL)
,('in voluptate velit esse cillum dolore eu fugia','et dolore magna aliqua. Ut enim ad min','cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ip',2751,1024120192.34,582,NULL)
,('ea commodo consequat. Duis aute irure dolor in reprehenderit in v','dolore eu fugia','in culpa qui officia deserunt mol',6532,1458722304.92,725,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla ','laboris nisi ut aliquip ex ea commodo consequat. Duis','ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate',892,994677376.30,372,NULL)
,('laborum.Lorem ipsum dolor sit amet, consec','id est laboru','occaecat cupidatat non pr',9034,892926784.51,248,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aut','laboris nisi ut aliquip ex ea commodo consequ','orum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut',25025,1858557568.89,485,NULL)
,('adipiscing elit, sed do e','laboris nisi ut aliquip ex ea commodo consequat. Duis aute ','in voluptate velit esse cillum dolo',10162,533139008.63,782,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui o','sed do eiusmod tempor incididunt ut labore et dolore m','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ip',18433,950368192.51,576,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing','lab','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit e',29919,1700183168.14,712,NULL)
,('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo con','tempor incididunt ut labore et dolore magna aliq','tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qui',16859,1339694976.00,246,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit','non proident, sunt in culpa qui officia deserunt mollit anim i','anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo',6444,1546525312.40,819,NULL)
,('elit, sed do eiusmod tempor incidi','Excepteur sint occaecat cup','velit e',9257,1547464704.62,164,NULL)
,('nisi ut aliquip ex ea commodo consequat. Duis aute irure dolo','incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exerci','Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea ',3523,675242560.26,861,NULL)
,('velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint oc','ipsum dolor sit amet,','voluptate velit esse cillum dolore eu',15522,973236032.79,787,NULL)
,('ci','ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit','exercitation ulla',25643,1850943488.25,167,NULL)
,('in ','Duis aute irure','aliquip ex ea commodo co',31631,1425968768.71,335,NULL)
,('n','dolor sit amet, consect','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit',3807,14348755.53,664,NULL)
,('ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in repre','ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi','elit, s',5951,4516757.76,856,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('deserunt mollit anim id est laborum.Lorem ips','deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consect','laboris nisi ut aliquip ex ea commodo consequat.',26716,1196386560.58,830,NULL)
,('Duis aute iru','ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit ','ullamco laboris nisi ut aliqui',5903,1233467008.31,832,NULL)
,('labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud','sint occaecat cupidatat non proident, sunt in culpa qui','non proident, sunt in culpa qui officia deserunt mollit anim id est lab',6455,926359744.98,284,NULL)
,('pariatur. Excepteur si','e','velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non ',21038,1104840448.59,984,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate','commodo consequat. Duis aute irure dolor in reprehenderit in volupta',18830,1843203072.10,20,NULL)
,('um.Lorem ipsum dolor sit ame','dolor in reprehenderit in voluptate velit esse cillum dolore e','ex ea co',14056,1157329408.17,274,NULL)
,('non proident, sunt in culpa qui off','adipisc','consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ',15743,290078624.86,329,NULL)
,('veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea comm','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia ','d',30202,924394240.41,859,NULL)
,('ad minim veniam, quis nostru','elit, sed do eius','aliqua. Ut enim ad minim veniam, quis nostrud exer',22621,367490880.98,419,NULL)
,('Ut enim ad minim v','dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in cu','quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure d',2742,1070273664.92,872,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('deserunt mollit anim i','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deser','ut labore',13641,1159977472.70,387,NULL)
,('ut aliquip ex ea comm','non proident, sunt in culpa qui officia deserunt mollit anim id est','irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',22642,115161056.26,136,NULL)
,('quis nostrud exercitatio','ex ea commodo consequat. Duis aute i','nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ',17893,1580881280.85,231,NULL)
,('consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia','deserunt mollit anim id est laborum.Lorem ips',12824,1061626816.31,804,NULL)
,('mollit anim id ','irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ','tempor incididunt ut labore et dolore magna aliqua. Ut en',8198,1686583936.95,351,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipis','incididunt ut labore e','Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea c',16152,1255895040.81,723,NULL)
,('et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla','veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex','adipiscing elit, sed do eiusmod tempor incididunt ut labore ',20574,1453965952.00,784,NULL)
,('do eiusmo','Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat n','do eiusmod tempor incididun',32338,325699264.63,880,NULL)
,('nulla pariatur. Excepteur sin','exercitation ullam','dolor',7434,1115073152.20,658,NULL)
,('ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation u','um.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in','in culpa qui officia deserunt ',6111,286693120.43,449,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('aute irure dolor','est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed','sint oc',24854,1686708992.57,16,NULL)
,('veniam, quis nostrud exercitation ullamco ','in reprehenderit in voluptate velit ','Excepteur sint occaecat cupidatat non proident, sunt in ',30013,1512069632.10,647,NULL)
,('dolore eu fugiat nulla pariatur. ','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim','pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offici',10033,262511264.97,384,NULL)
,('enim ad minim veniam, quis nostrud ex','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamc','velit esse cillum dolore eu fugiat nulla',13774,775274048.20,938,NULL)
,('tempor incididunt ut labore et dolore magna aliqua. Ut','adipiscing','elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',28718,552032320.43,112,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi','m','in culpa qui officia deserunt mollit anim id est laborum.Lo',24290,1474198784.59,552,NULL)
,('sint occaecat cupidatat non proident, sunt in culpa qui officia d','ipsum dolor sit amet, consectetur adipiscing eli','sit amet, consectetur adipiscing e',1320,135786144.48,37,NULL)
,('aute iru','n','Duis aute ir',952,1318258304.41,954,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo cons','adipiscing elit, s','exercitati',26531,1433660416.13,292,NULL)
,('eu fugiat nulla pariatur. Except','sit a','in v',10488,1419246976.47,240,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit am','nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia ','qui officia deserunt mollit anim id est laborum.Lorem ipsum',2710,1261150208.80,321,NULL)
,('magna aliqua. Ut enim ad minim veniam, quis nostrud exerc','Excepteur sint occaecat cupidatat non proident, s','nulla pariatur. Excepteur sint occaecat cupidatat non',19504,305167296.75,223,NULL)
,('dolor in repr','sit amet, consectetur adipiscing elit, sed do eiusmod te','sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor si',6886,608429504.30,706,NULL)
,('incididunt ut labore et','reprehenderit ','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit a',10460,1422842496.74,557,NULL)
,('labore et dolore magn','sunt in culpa qui o','sunt in culpa qui off',10382,548696576.38,915,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute i','consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore','elit, sed do eiusmod tempor incididu',6445,1620872192.39,518,NULL)
,('quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea','temp','incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud',19794,473964192.35,910,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, consectet','elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ','pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui offici',484,1125309184.79,990,NULL)
,('amet, consectetur adipiscing elit, sed ','consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolo','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru',30593,30524014.96,76,NULL)
,('sit amet, consectetur adipiscing elit, sed do eiusmod tempor','velit esse cillum dolore eu fugiat nulla pariatur. Exc','velit esse cillum dolore eu fugiat',12240,1385811968.44,144,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('Excepteur sint occaec','sit amet, consectetur adipiscing e','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum',21952,371681408.85,884,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt','sed do ei','magna aliqua. Ut eni',253,614193984.33,763,NULL)
,('incididunt ut labore et dolore magna aliqua. Ut eni','cillum dolore eu fugiat nulla pariatur. Excepteur sint ','qui officia deserunt mollit anim id est laborum.Lorem ipsum dolo',14604,512616288.20,187,NULL)
,('commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor','non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum','Excepteur sint ',3837,1407616000.41,488,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla ','exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat','Duis aute irure dolor in reprehenderit in voluptate ve',25323,1224819840.10,473,NULL)
,('eu fugiat nulla pariatur. E','ut labore ','in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupida',26105,1134310016.19,87,NULL)
,('in voluptate velit esse cillum dolore eu fugiat nulla paria','nulla pariatu','sint occaecat cupi',4870,619129280.66,89,NULL)
,('laboris nisi ut aliquip ex ea commodo consequat. Duis aute i','mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiu','sed do eiusmod tempor incididunt ut labore et dolore',1804,1073637760.90,67,NULL)
,('nulla pariatur. Excepteur sin','pariatur. Excepteu','id est laborum.Lorem ipsum dol',12666,548577344.50,54,NULL)
,('sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor','magna aliqua. Ut enim ad mini','amet, consectetur adipiscing',8194,167867888.62,72,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui','tempor incididunt ut labore et dolore magna aliqua. Ut enim ','anim id est laborum.Lorem ipsum dolor s',26266,220467328.89,74,NULL)
,('ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt','dolor in reprehe','sed do eiusmod tempor incididunt ut labore et dolore magna aliq',1534,160285280.87,215,NULL)
,('consequat. Duis aute ','ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation','eiusmod tempor incididunt ut labore et dolo',4824,497347584.91,465,NULL)
,('occaecat cupidatat non proident, su','quis nostrud exercitati','Ut enim ad minim veniam,',9491,912811712.63,670,NULL)
,('minim veniam, quis n','eu fugiat nu','in voluptate velit e',23806,598342016.73,24,NULL)
,('id est laborum.Lorem ipsum dolor sit amet, co','minim veniam,','ullamco laboris nisi ut aliquip ex ea commodo consequ',10472,1532898944.29,710,NULL)
,('a','nulla pariatur. Excepteur sint o','magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio',4656,1605422848.29,598,NULL)
,('tempor incididunt ut la','in reprehenderit in voluptate velit esse cillum dolor','adipisci',8956,1013156416.34,480,NULL)
,('ipsum dolor sit amet, consectetur adipisci','e','dolore eu fugiat nulla paria',10026,445486816.36,967,NULL)
,('laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d','dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui o','laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit i',10608,533356928.34,150,NULL)
;
INSERT INTO SampleProducts.dbo.Products (Name,ShortDescription,Description,Quantity,Price,BrandId,[TimeStamp]) VALUES 
('ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse ','nostr','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit',9319,1846039808.27,689,NULL)
,('amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore','velit esse cillum dolore eu fugiat nulla pariatur. ','id est laborum.Lorem ipsum dolor sit',26498,7009875.65,65,NULL)
,('dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in','adipiscing elit, sed do eiusmod tempor incididunt ut','in r',1984,230419680.50,23,NULL)
,('amet','Exce','um.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ei',14606,1101613568.83,382,NULL)
,('pariat','aute irure dolor in reprehenderit in voluptate velit ess','qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, cons',7511,101536584.12,918,NULL)
,('est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp','eu fugiat nulla pariatur. Excepteur sint','Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim i',10607,1208529920.59,401,NULL)
,('eu fugiat nulla','tempor incididunt ut labore et dolore magna aliqua. Ut eni','adipiscing elit, sed do eiusmod tempor incididunt ut labore et dol',23522,1586852096.57,143,NULL)
,('quis nostrud exercitation ullamco ','laboris nisi ut aliquip ex ea commodo conseq','ea commodo consequat. Duis aute i',5226,1110586880.65,943,NULL)
,('Duis aute irure dolor in reprehenderit in voluptate velit esse cillu','in voluptate velit esse cillum dolore eu fug','dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sin',808,1137121664.33,908,NULL)
;